ALTER TABLE "Budget" ADD COLUMN IF NOT EXISTS "signedCpf" TEXT;
ALTER TABLE "Budget" ADD COLUMN IF NOT EXISTS "signedGovLevel" TEXT;
ALTER TABLE "Budget" ADD COLUMN IF NOT EXISTS "signedDocHash" TEXT;
