ALTER TABLE "Patient"  ADD COLUMN IF NOT EXISTS "photoUrl"  TEXT;
ALTER TABLE "Guardian" ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3);
ALTER TABLE "Guardian" ADD COLUMN IF NOT EXISTS "cep"       TEXT;
