ALTER TABLE "CatalogItem" ADD COLUMN "stockEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CatalogItem" ADD COLUMN "stockQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CatalogItem" ADD COLUMN "stockMin" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Budget" ADD COLUMN "signedAt" TIMESTAMP(3);
ALTER TABLE "Budget" ADD COLUMN "signatureData" TEXT;
